# Generated by Django 4.2.2 on 2023-06-26 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_profile_photo_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="department",
        ),
    ]
